### ISSUE TITLE
Enemy AI 

### ISSUE THREAD

**Issue by TRG-T** [J-A-F/DECREE#16]
# Enemy AI
Enemy AI should be able to find the best route to take in the air and on land (by enemy type) in the current situation (take obstacles into account), should have a field of vision, jump, shoot, hit, designate patrols when it cannot see the player

## TODOs
- [ ] Following the player
- [ ] Hitting a player
- [ ] Shooting the player
- [ ] Field of vision
- [ ] Patrols
- [ ] Best route on land
- [ ] Best route in air

## Resources

None for now

## Known bugs & blockers

None for now

## Linked issues & PRs

[Epic](https://github.com/J-A-F/DECREE/issues/13)
